// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

extern int page_index;
extern int all_close_flag;
extern int dir_change_flag;

void all_close(lv_event_t *e)
{
	// Your code here
	all_close_flag = 1;
}

void page_a_func(lv_event_t *e)
{
	// Your code here
	page_index = 1;
}

void page_b_func(lv_event_t *e)
{
	// Your code here
	page_index = 2;
}

void page_main_func(lv_event_t *e)
{
	// Your code here
	page_index = 0;
}

void dir_change(lv_event_t *e)
{
	// Your code here
	dir_change_flag = 1;
}
