// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

extern int time_shift_index;
extern int rtc_set_flag;
extern int page_index;

extern int relay_flag;
extern int relay_state;
extern int all_open_flag;
extern int all_close_flag;

extern int alarm_set_flag;
extern int alarm_load_flag;
extern int alarm_reset_flag;
extern int alarm_store_flag;


void time_shift(lv_event_t *e)
{
	// Your code here
	time_shift_index++;
	time_shift_index %= 3;
}

void set_time(lv_event_t *e)
{
	// Your code here
	rtc_set_flag = 1;
	page_index = 1;
}

void set_relay(lv_event_t *e)
{
	// Your code here
	page_index = 2;
	alarm_load_flag = 1;
}

void all_close(lv_event_t *e)
{
	// Your code here
	all_close_flag = 1;
}

void all_open(lv_event_t *e)
{
	// Your code here
	all_open_flag = 1;
}

void relay_switch(lv_event_t *e)
{
	// Your code here
	relay_state = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);
	relay_flag = 1;
}

void set_alarm(lv_event_t *e)
{
	// Your code here
	alarm_set_flag = 1;
}

void reset_alarm(lv_event_t *e)
{
	// Your code here
	alarm_reset_flag = 1;
}

void leave_set_relay(lv_event_t *e)
{
	// Your code here
	page_index = 1;
	alarm_store_flag = 1;
}
