// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Dropdown1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label7;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Label1;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Arc2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Label12;
void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Arc6;
extern lv_obj_t * ui_Arc7;
extern lv_obj_t * ui_Arc8;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel1;
void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Label13;
void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_Label17;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_Label8;
void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Label14;
void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_Label15;
void ui_event_ImgButton11(lv_event_t * e);
extern lv_obj_t * ui_ImgButton11;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
void ui_event_Screen7(lv_event_t * e);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Image1;
// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_a12_png);    // assets/a12.png
LV_IMG_DECLARE(ui_img_12_png);    // assets/12.png
LV_IMG_DECLARE(ui_img_button1_png);    // assets/button1.png
LV_IMG_DECLARE(ui_img_button2_png);    // assets/button2.png
LV_IMG_DECLARE(ui_img_8_png);    // assets/8.png
LV_IMG_DECLARE(ui_img_10_png);    // assets/10.png
LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_11_png);    // logo
// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
