// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void set_voltage(lv_event_t * e);
void set_page3(lv_event_t * e);
void set_page6(lv_event_t * e);
void change_channel_1(lv_event_t * e);
void change_channel_2(lv_event_t * e);
void set_page4(lv_event_t * e);
void set_page2(lv_event_t * e);
void all_close(lv_event_t * e);
void set_page5(lv_event_t * e);
void set_rgb_index(lv_event_t * e);
void set_color_mode(lv_event_t * e);
void set_fresh_mode(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
