// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

extern int voltage_index;
extern int voltage_flag;
extern int page_index;
extern int rgb_index;
extern int led_channel;
extern int on_off_flag;
extern int mode_index;
extern int mode_flag;
extern int rd_color_index;
extern int rd_color_flag;

void set_voltage(lv_event_t *e)
{
	// Your code here
	voltage_index = lv_dropdown_get_selected(ui_Dropdown1);
	voltage_flag = 1;
	page_index = 2;
}

void set_rgb_index(lv_event_t *e)
{
	// Your code here
	rgb_index = (rgb_index + 1) % 3;

	if (rgb_index == 0)
		lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
	if (rgb_index == 1)
		lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
	if (rgb_index == 2)
		lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
}

void set_page2(lv_event_t *e)
{
	// Your code here
	page_index = 2;
}

void set_page3(lv_event_t *e)
{
	// Your code here
	page_index = 3;
}
void set_page4(lv_event_t *e)
{
	// Your code here
	page_index = 4;
}

void set_page5(lv_event_t *e)
{
	// Your code here
	page_index = 5;
}

void set_page6(lv_event_t *e)
{
	// Your code here
	page_index = 6;
}

void change_channel_1(lv_event_t *e)
{
	// Your code here
	led_channel = 0;
}

void change_channel_2(lv_event_t *e)
{
	// Your code here
	led_channel = 1;
}

void all_on_off(lv_event_t * e)
{
	// Your code here
	on_off_flag = 1;
}

void set_color_mode(lv_event_t *e)
{
	// Your code here
	rd_color_index = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);
	rd_color_flag = 1;
}

void set_fresh_mode(lv_event_t *e)
{
	// Your code here
	mode_index = lv_dropdown_get_selected(ui_Dropdown2);
	mode_flag = 1;
}
