// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

extern int page_index;
extern int stepper_index;
extern int home_reset_flag;
extern int rpm_flag;
extern int dir_change_flag;
extern int work_mode;

void page_to_2(lv_event_t * e)
{
    // Your code here
    page_index = 2;
}

void page_to_4(lv_event_t * e)
{
    // Your code here
    page_index = 4;
    rpm_flag = 1;
}

void page_to_3(lv_event_t * e)
{
    // Your code here
    page_index = 3;
}

void page_to_1(lv_event_t * e)
{
    // Your code here
    page_index = 1;
    work_mode = 0;
}

void change_stepper(lv_event_t * e)
{
    // Your code here
    stepper_index = !stepper_index;
}

void home_reset(lv_event_t * e)
{
    // Your code here
    home_reset_flag = 1;
}

void dir_change(lv_event_t * e)
{
    // Your code here
    dir_change_flag = 1;
}