// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void page_to_2(lv_event_t * e);
void page_to_4(lv_event_t * e);
void page_to_3(lv_event_t * e);
void page_to_1(lv_event_t * e);
void change_stepper(lv_event_t * e);
void home_reset(lv_event_t * e);
void dir_change(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
