// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

extern int page_index;
extern int sd_update_flag;

void change_page_2(lv_event_t * e)
{
	// Your code here
	page_index = 1;
}

void change_page__1(lv_event_t * e)
{
	// Your code here
	page_index = 0;
}
